target-version = "py312"
line-length = 150

exclude = [
  "docs/",
  "extra/",
  ".obsidian_ai_cache/",
  "__pycache__/",
  ".venv/",
  ".git/",
]

[lint]
select = [
  "F",      # Pyflakes
  "W",      # pycodestyle warnings
  "UP",     # pyupgrade
  "C4",     # flake8-comprehensions
  "RET",    # flake8-return
  "A",      # flake8-builtins
  "FURB",   # refurb
  "RUF",    # Ruff-specific rules
]

ignore = [
  "E111",   # indentation is not a multiple of 4
  "E114",   # indentation is not a multiple of 4 (comment)
  "E501",   # line too long (handled by formatter)
]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "F841",   # unused variable
  "A",      # builtin shadowing in tests is ok
  "RET506", # superfluous else in tests is ok
  "RET507", # superfluous else in tests is ok
]